using New_LeRayBookingSystem.Data;
using New_LeRayBookingSystem.Models;
using New_LeRayBookingSystem.Services;
using New_LeRayBookingSystem.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;

namespace New_LeRayBookingSystem.Controllers
{
    public class ApplicationUsersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailService _emailService;

        public ApplicationUsersController(
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            IEmailService emailService)
        {
            _context = context;
            _userManager = userManager;
            _emailService = emailService;
        }

        // ✅ GET: ApplicationUsers
        public async Task<IActionResult> Index()
        {
            var users = await _context.Users
                .Select(u => new ApplicationUserViewModel
                {
                    Id = u.Id,
                    FullName = u.FullName,
                    DateJoined = u.DateJoined
                })
                .ToListAsync();

            return View(users);
        }

        // ✅ GET: ApplicationUsers/Details/5
        public async Task<IActionResult> Details(string? id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return NotFound();

            var user = await _context.Users.FindAsync(id);
            if (user == null)
                return NotFound();

            return View(MapToViewModel(user));
        }

        // ✅ GET: ApplicationUsers/Create
        public IActionResult Create()
        {
            return View();
        }

        // ✅ POST: ApplicationUsers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ApplicationUserViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            // Sanitize input
            var fullName = string.IsNullOrWhiteSpace(model.FullName) ? "Unnamed User" : model.FullName.Trim();
            // ✅ Auto-generate a unique email
            var baseEmail = Regex.Replace(fullName.ToLower(), @"\s+", "");
            var email = $"{baseEmail}@leray.com";
            int counter = 1;
            while (await _userManager.FindByEmailAsync(email) != null)
            {
                email = $"{baseEmail}{counter}@leray.com";
                counter++;
            }

            // ✅ Construct user (ID auto-generated by ApplicationUser)
            var user = new ApplicationUser(fullName)
            {
                UserName = email,
                Email = email,
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow,
                DateJoined = DateTime.UtcNow
            };

            // ✅ Temporary secure password
            var password = $"User@{Guid.NewGuid():N}".Substring(0, 12);

            // ✅ Save to Identity
            var result = await _userManager.CreateAsync(user, password);

            if (result.Succeeded)
            {
                // Assign to default role
                await _userManager.AddToRoleAsync(user, "Client");

                // ✅ Send Welcome Email
                await _emailService.SendEmailAsync(
                    user.Email!,
                    "Welcome to LeRay Booking System",
                    $@"<p>Hello {user.FullName},</p>
                       <p>Your account has been created successfully!</p>
                       <p><b>Login Email:</b> {user.Email}</p>
                       <p><b>Temporary Password:</b> {password}</p>
                       <p>Please change your password after logging in.</p>
                       <p>Thank you,<br/>LeRay Team</p>"
                );

                return RedirectToAction(nameof(Index));
            }

            // Handle Identity validation errors
            foreach (var error in result.Errors)
                ModelState.AddModelError(string.Empty, error.Description);

            return View(model);
        }

        // ✅ GET: ApplicationUsers/Edit/5
        public async Task<IActionResult> Edit(string? id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return NotFound();

            var user = await _context.Users.FindAsync(id);
            if (user == null)
                return NotFound();

            return View(MapToViewModel(user));
        }

        // ✅ POST: ApplicationUsers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, ApplicationUserViewModel model)
        {
            if (id != model.Id)
                return NotFound();

            if (!ModelState.IsValid)
                return View(model);

            var user = await _context.Users.FindAsync(id);
            if (user == null)
                return NotFound();

            user.FullName = model.FullName ?? user.FullName;
            user.UpdatedAt = DateTime.UtcNow;

            try
            {
                _context.Update(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!UserExists(user.Id))
                    return NotFound();
                throw;
            }
        }

        // ✅ GET: ApplicationUsers/Delete/5
        public async Task<IActionResult> Delete(string? id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return NotFound();

            var user = await _context.Users.FindAsync(id);
            if (user == null)
                return NotFound();

            return View(MapToViewModel(user));
        }

        // ✅ POST: ApplicationUsers/DeleteConfirmed
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        // ✅ Helpers
        private bool UserExists(string id) =>
            _context.Users.Any(e => e.Id == id);

        private static ApplicationUserViewModel MapToViewModel(ApplicationUser user) => new()
        {
            Id = user.Id,
            FullName = user.FullName,
            DateJoined = user.DateJoined
        };
    }
}
