using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace New_LeRayBookingSystem.Models
{
    // This attribute explicitly tells Entity Framework Core to map this model 
    // to the 'customerservices' table in the database.
    [Table("customerservices")] 
    public class CustomerService
    {
        [Key]
        // This attribute tells EF Core that the 'Id' column is the primary key
        // and its value is generated by the database (e.g., AUTO_INCREMENT).
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string ServiceName { get; set; } = string.Empty;

        [Required]
        [StringLength(50)]
        public string Category { get; set; } = string.Empty;

        [Column(TypeName = "decimal(10, 2)")]
        public decimal Price { get; set; }

        // Time represents the Duration column in MySQL
        public TimeSpan Duration { get; set; } 

        [Required]
        public bool IsBundle { get; set; } = false;


        [StringLength(255)]
        public string? Description { get; set; }
        
        // --- Navigation Properties (if needed) ---
        // public ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();
    }
}